Apps/Aplicacion1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required
#from django.contrib.auth.views import login
from django.conf.urls import url,include
from .views import * 

#IndexView,crearinventarioView,crearempleadoView,crearventaView,creardetalleView,listainventarioView,listaempleadoView,listadetallefacturaView,precio_detalleV,inventarioeditar

urlpatterns = [
url(r'^$',IndexView.as_view(),name='index'),
url(r'^inventario/$',crearinventarioView.as_view(),name='inventario'),
url(r'^empleado/$',crearempleadoView.as_view(),name='empleado'),
url(r'^venta/$',crearventaView.as_view(),name='venta'),
url(r'^detalleventa/$',creardetalleView.as_view(),name='detalleventa'),
url(r'^listadoinventario/$',listainventarioView.as_view(),name='listadoinventario'),
url(r'^listadoempleado/$',listaempleadoView.as_view(),name='listadoempleado'),
url(r'^listadodetallefactura/$',listadetallefacturaView.as_view(),name='listadodetallefactura'),
url(r'^precio/$',precio_detalleV,name='precio_detalle'),
#url(r'^$',login,{'base':'index.html'}, name='login'),
#path('login', LoginView.as_view(template_name='registration/login.html'), name="login"),
#path('login/', LoginView.as_view(template_name='crearempleado.html'), name="login"),
#url(r'^editar/<int:codig>$',editarinventarioView, name= 'editarinventario')
path('editar_inventario/<pk>',(inventarioeditar.as_view()),name='editar_inventario'),
path('editar_empleado/<pk>',(empleadoeditar.as_view()),name='editar_empleado'),
path('eliminar_inv/<pk>/',(eliminar_inventario.as_view()),name='eliminar_inv'),
path('eliminar_empleado/<pk>/',(eliminar_empleado.as_view()),name='eliminar_empleado'),
#url(r'^editar_inventario/(?P<pk>\d+>)/$', inventarioeditar.as_view(), name='editar_inventario'),
#url(r'^eliminar_inv/(?P<pk>\d+>)/$', eliminar_inventario.as_view(),name='eliminar_inv'),
]

Apps/usuario/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.conf.urls import url,include
from .views import * 
urlpatterns = [
	
url(r'^registrar/$', Registro_usuario.as_view(),name='registrar'),
 #path('registrar/',(Registro_usuario.as_view()),name='registrar'),
 ]

primerproyecto/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

urlpatterns = [
url(r'^admin/',admin.site.urls),
url(r'^App1/',include(('Apps.Aplicacion1.urls','app1'), namespace='app1')),
url(r'^App2/',include(('Apps.usuario.urls','app2'), namespace='app2')),
path('login/', auth_views.LoginView.as_view(), name='login'),

 ]

Apps/Aplicacion1/models.py
from django.db import models
class inventario(models.Model):
	codigo_inventario = models.IntegerField(primary_key=True)
	nombre_inventario = models.CharField(max_length=25)
	marca_invetario = models.CharField(max_length=25)
	existencia_inventario = models.IntegerField()
	precio_inventario = models.FloatField()
	estado = models.BooleanField(default=True, verbose_name='estado')

	def __str__(self):
		return '%s %s %s %s %s %s' % (self.codigo_inventario,self.nombre_inventario,self.marca_invetario,self.existencia_inventario,self.precio_inventario,self.estado)


class empleado(models.Model):
	codigo_empleado =models.IntegerField(primary_key =True)
	nombre_empleado =models.CharField(max_length=25)
	email_empleado =models.EmailField(max_length=25)
	fecha_empleado =models.DateField()

	def __str__(self):
		return '%s %s %s %s' % (self.codigo_empleado,self.nombre_empleado,self.email_empleado,self.fecha_empleado)

class venta(models.Model):
	codigo_empleado = models.ForeignKey(empleado, on_delete=models.CASCADE)
	codigo_venta = models.AutoField(primary_key = True)
	fecha_venta = models.DateField()
	total_venta = models.FloatField()
	


	def __str__(self):
		return '%s %s %s %s' % (self.codigo_empleado,self.codigo_venta,self.fecha_venta,self.total_venta)

class detallefactura(models.Model):
	codigo_detalle = models.AutoField(primary_key = True)
	codigo_venta = models.ForeignKey(venta, on_delete=models.CASCADE)
	codigo_inventario = models.ForeignKey(inventario, on_delete=models.CASCADE)
	cantidad_producto = models.IntegerField()
	Precio_unitario = models.FloatField()
	precio_total = models.FloatField()
	fecha_detalle = models.DateField()


	def __str__(self):
		return '%s %s %s %s %s %s %s' % (self.codigo_detalle,self.codigo_venta,self.codigo_inventario,self.cantidad_producto,self.Precio_unitario,self.precio_total,self.fecha_detalle)

Apps/Aplicacion1/forms.py
from django import forms
from .models import inventario,empleado,venta,detallefactura
from django.forms import ModelForm

class inventarioForm(ModelForm):

	class Meta:
		model = inventario

		fields = [
				'codigo_inventario',
				'nombre_inventario',
				'marca_invetario',
				'existencia_inventario',
				'precio_inventario',
		]
		labels = {

				'codigo_inventario': 'Codigo del inventario',
				'nombre_inventario': 'Nombre del producto',
				'marca_invetario': 'Marca del producto',
				'existencia_inventario': 'Existencia del producto',
				'precio_inventario': 'Precio unitario',
		}
		widgets = {

				'codigo_inventario': forms.TextInput(attrs={'class':'form-control'}),
				'nombre_inventario': forms.TextInput(attrs={'class':'form-control'}),
				'marca_invetario': forms.TextInput(attrs={'class':'form-control'}),
				'existencia_inventario': forms.TextInput(attrs={'class':'form-control'}),
				'precio_inventario' : forms.TextInput(attrs={'class':'form-control'}),
		}


class empleadoForm(ModelForm):

	class Meta:
		model = empleado
		fields = [
				'codigo_empleado',
				'nombre_empleado',
				'email_empleado',
				'fecha_empleado',

		]
		labels = {
				'codigo_empleado': 'Codigo del empleado',
				'nombre_empleado': 'Nombre del empleado',
				'email_empleado': 'E-mail',
				'fecha_empleado': 'Fecha de inicio',
		
		}
		widgets = {
				  'codigo_empleado': forms.TextInput(attrs={'class':'form-control'}),
				  'nombre_empleado': forms.TextInput(attrs={'class': 'form-control'}),
				  'email_empleado': forms.TextInput(attrs={'class': 'form-control'}),
				  'fecha_empleado': forms.SelectDateWidget(years=range(2019,2050)),


		}


class ventaForm(ModelForm):

	class Meta:
		model = venta
		fields =[
				'codigo_empleado',
				'codigo_venta',
				'fecha_venta',
				'total_venta',
		]
		labels= {
				'codigo_empleado': 'Codigo del empleado',
				'codigo_venta': 'Codigo de venta',
				'fecha_venta': 'Fecha de venta',
				'total_venta': 'Total de la venta',

		}
		widgets = {
				  'codigo_empleado': forms.Select(attrs={'class':'form-control'}),
				  'codigo_venta': forms.TextInput(attrs={'class': 'form-control'}),
				  'fecha_venta': forms.SelectDateWidget(years=range(2019,2050)),
				  'total_venta': forms.TextInput(attrs={'class': 'form-control'}),
		}
class detallefacturaForm(ModelForm):

	class Meta:
		model = detallefactura
		fields = [
				'codigo_venta',
				'codigo_inventario',
				'cantidad_producto',
				'Precio_unitario',
				'precio_total',
				'fecha_detalle',
		]
		labels ={
				'codigo_venta': 'Empleado',
				'codigo_inventario': 'Codigo de venta',
				'cantidad_producto': 'Cantidad',
				'Precio_unitario': 'Precio del producto',
				'precio_total': 'Total',
				'fecha_detalle': 'Fecha',

		}
		widgets = {
			'codigo_inventario': forms.Select(attrs={'id':'idproducto'}),
			 'fecha_detalle': forms.SelectDateWidget(years=range(2019,2050)),
		}

	def __init__(self, *args, **kwargs):
		super(detallefacturaForm, self).__init__(*args, **kwargs)
		#self.fields['codigo_inventario'].widget.attrs\
        #    .update({
        #        'id': 'codigo'
        #    })
		self.fields['Precio_unitario'].widget.attrs\
            .update({
                'id': 'precio'
            })

Apps/Aplicacion1/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView,CreateView,ListView,UpdateView,DeleteView
from .forms import inventarioForm,empleadoForm,ventaForm,detallefacturaForm
from .models import inventario,empleado,venta,detallefactura
from django.urls import reverse_lazy
from django.http import JsonResponse


# Create your views here.
class IndexView(TemplateView):
		template_name='index.html'

class NuevaFacturaView(TemplateView):
		template_name='factura.html'


class prueba1View(TemplateView):
		template_name='prueba1.html'


class creditosView(TemplateView):
		template_name='creditos.html'

class crearinventarioView(CreateView):
		template_name = 'crearinventario.html'
		model = inventario
		form_class = inventarioForm
		success_url = reverse_lazy ('app1:listadoinventario')

class crearempleadoView(CreateView):
		template_name = 'crearempleado.html'
		model = empleado
		form_class = empleadoForm
		success_url = reverse_lazy ('app1:listadoempleado')

class crearventaView(CreateView):
		template_name = 'crearventa.html'
		model = venta
		form_class = ventaForm
		success_url = reverse_lazy ('app1:detalleventa')

class creardetalleView(CreateView):
		template_name = 'creardetallefactura.html'
		model = detallefactura
		form_class = detallefacturaForm
		success_url = reverse_lazy ('app1:listadodetallefactura')

class listainventarioView(ListView):
	template_name = 'listadoinventario.html'
	model = inventario
get_queryset= inventario.objects.filter(estado=True)

class listaempleadoView(ListView):
	template_name = 'listadoempleado.html'
	model = empleado
	def get_queryset(self):
		return empleado.objects.all()

class listadetallefacturaView(ListView):
	template_name = 'listadodetallefactura.html'
	model = detallefactura
	def get_queryset(self):
		return detallefactura.objects.all()

class inventarioeditar(UpdateView):
	model = inventario
	form_class = inventarioForm
	template_name ='crearinventario.html'
	success_url = reverse_lazy ('app1:listadoinventario')


class empleadoeditar(UpdateView):
	model = empleado
	form_class = empleadoForm
	template_name ='crearempleado.html'
	success_url = reverse_lazy ('app1:listadoempleado')


class eliminar_inventario(DeleteView):
	model = inventario
	form_class = inventarioForm
	template_name ='inventario_confirm_delete.html'
	success_url = reverse_lazy ('app1:listadoinventario')
	

class eliminar_empleado(DeleteView):
	model = empleado
	form_class = empleadoForm
	template_name ='inventario_confirm_delete.html'
	success_url = reverse_lazy ('app1:listadoempleado')
	

#def editarinventarioView(request, codigo_inventario):
	#inventarios = inventario.objects.get(codigo_inventario=codigo_inventario)
	#if request.method =='GET':
		#form = inventarioForm(instance = inventarios)
	#else: 
		#form = inventarioForm(request.POST, instance = inventarios)
		#if form.is_valid():
		#	form.save()
		#	return redirect('app1:listadoinventario')
		#	return render (request, 'app1/crearinventario.html', {'form':form})

def precio_detalleV (request):
	codigo = request.GET['codigo']
	data = {
	'existencia': inventario.objects.only('precio_inventario').get(codigo_inventario=codigo).precio_inventario
	}

	return JsonResponse(data)

	#if request.method == 'POST':
	#	precio_b = request.POST['idproducto']
	#else :
	#	precio_b = ''

	#inventarios = inventario.objects.filter(codigo_inventario=precio_b)

	#return render_to_response('ajax_precio.html',{'inventarios':inventarios})

Apps/Aplicacion1/templates/ajax_precio.html
{% if inventarios > 0 %}

{% for inven in inventarios %}

	<input type="text">{{inven.precio_inventario}}</input>

{% end for %}

{% else %}

<a href="#">Nada</a>

{% end if %}

Apps/Aplicacion1/templates/base.html
{% load static %}
<!doctype html>
<html lang="es">
    <head>
        <!-- Required meta tags -->
         <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Cardigan</title>

  <!-- Bootstrap core CSS -->
  
  <link rel="stylesheet" href="{% static 'boot/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/css/estilos.css' %}">


        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/popup/magnific-popup.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'jsyo/script.js' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'jsyo/jquery.js' %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
  
</head>

<body  background="{% static 'boot/img/fondo.jpeg' %}" >
<div class="fondo">
    <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark  static-top" style="background-color: #005a65;" >
        <div class="container">
         <a class="navbar-brand" href="#">
              <img src="{% static 'boot/img/logo.png' %}" width="80" height="80">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
              <ul class="nav navbar-nav menu_nav ml-auto">
              
                <li class="nav-item"> <a class="nav-link" href="{% url 'app1:index' %}">Principal</a>
                <li class="nav-item"> <a class="nav-link" href="{% url 'app1:listadoempleado' %}">Empleado</a>
                <li class="nav-item"> <a class="nav-link" href="{% url 'app1:listadoinventario' %}">Inventario</a>
                <li class="nav-item"> <a class="nav-link" href="{% url 'app1:venta' %}">Ventas</a>
                   <li class="nav-item"> <a class="nav-link" href="{% url 'app2:registrar' %}">Crearusuario</a>
                                
              </ul>
            </div> 
          </div>
          
      </nav>
       {% block contenido %}
      
          {% endblock %}

          {% block prueba1 %}
      
          {% endblock %}
      <br><br><br>
    
      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      <script src="vendor/jquery/jquery.slim.min.js"></script>
      <script src="{% static 'js/ajax.js' %}"></script>
      <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


</div>

    </body>
</html>

Apps/Aplicacion1/templates/creardetallefactura.html
{% extends 'base.html' %}

{% block contenido %}

<table width="450"  align=center>
    <tr>
        <td>
			<form method='POST'>
					<div class="form-row">

				{% csrf_token%}
				{{form.as_p}}
					</div>

				<div id="precioR"></div>
				<input type="submit" name="exit">
				
			</form>
			<br>
			<a href="{% url 'app1:listadodetallefactura' %}"><strong><u><font size ="5", color="#2271b3">Listado de facturas</font></u></strong></a>
			
		<td>	
	</tr>


</table>

{% endblock %}

Apps/Aplicacion1/templates/crearempleado.html
{% extends 'base.html' %}

{% block contenido %}
<br><br>
<table width="400"  align=center>
    <tr>
        <td>

        	<form method='POST' >

        		
			{% csrf_token%}
			{{form.as_p}}
				
	
			<br>
			<div >
				<div class="col_md_8 col-md-offset-2">
					<div class="form-group">
						<button class= "btn btn-primary"input type="submit">Guardar</button>
					</div>
					
				</div>
				
			</div>
		</form>

	
<br>
	


        </td>
    </tr>
    </table>
		
{% endblock %}

Apps/Aplicacion1/templates/crearinventario.html
{% extends 'base.html' %}

{% block contenido %}

<table width="450"  align=center>
    <tr>
        <td>

        	<form method='POST' >
        		<div class="form-row">

			{% csrf_token%}
			{{form.as_p}}
				</div>



			<div >
				<div class="col_md_8 col-md-offset-2">
					<div class="form-group">
						<button class= "btn btn-primary"input type="submit">Guardar</button>
					</div>
							
				</div>
						
			</div>
			
		</form>
		
		

        

        </td>
    </tr>
    </table>

		
	

{% endblock %}

Apps/Aplicacion1/templates/crearventa.html
{% extends 'base.html' %}

{% block contenido %}
<br><br>
<table width="400"  align=center>
    <tr>
        <td>

        	<form method='POST' >
        		<div class="form-row">
			{% csrf_token%}
			{{form.as_p}}
			<br>
				</div>

			<div >
				<div class="col_md_8 col-md-offset-2">
					<div class="form-group">
						<button class= "btn btn-primary center-block" type="submit" style="">Guardar</button>
					</div>
					
				</div>
				
			</div>
			
		</form>

<br>
<div>
		<div class="form-group">
			<a href="{% url 'app1:detalleventa' %}"><strong><u><font size ="5", color="#2271b3">Detalle de la factura</u></strong></a>
		</div>
			
</div>

        </td>
    </tr>
</table>
		

{% endblock %}

Apps/Aplicacion1/templates/factura.html
{% extends 'base.html' %}

{% block contenido %}

{% endblock %}
       

Apps/Aplicacion1/templates/index.html
{% extends 'base.html' %}

{% block contenido %}
<form method="POST">
  
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" style="color: black; font-style: oblique">
      <br><br><br><br><br><br><br>
      <h1 align="center">Bienvenidos a Cardigan Store</h1>
    </div>
    <div class="carousel-item">
     <h3>ASF</h3>
      </div>
    <div class="carousel-item">
    <H1>12345</H1>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

</form>
{% endblock %}

       

Apps/Aplicacion1/templates/inventario_confirm_delete.html
{% extends 'base.html' %}

{% block contenido %}

        	<form method='POST' >

			{% csrf_token%}
	

			<p> <strong>¿desea eliminar el registro{{ object }} ?</strong></p>
			<button type="submit" class="btn btn-danger">Confirmar</button>


			
		</form>
		
		
	

{% endblock %}

Apps/Aplicacion1/templates/listadodetallefactura.html
{% extends 'base.html' %}

{% block contenido %}
<br><br>
<h2><center>listado de facturas</center></h2>
<br>
<table border="1" class="table table-striped" >
	<tr>
		<td class="danger"><font size ="3", color="black"><strong>Codigo de factura</strong></td>
		<td class="danger"><font size ="3", color="black"> <strong>Nombre de venta</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>Codigo de producto</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>Cantidad de producto</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>Precio unitario</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>Precio total</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>Fecha factura</strong></td>

		
	</tr>
	{% for  est in object_list %}
	<tr>
		<td > {{ est.codigo_detalle}}</td>
		<td > {{ est.codigo_venta}}</td>
		<td > {{ est.codigo_inventario}}</td>
		<td > {{ est.cantidad_producto}}</td>
		<td > {{ est.Precio_unitario}}</td>
		<td > {{ est.precio_total}}</td>
		<td > {{ est.fecha_detalle}}</td>
	</tr>
	{% endfor %}
</table>


{% endblock %}

Apps/Aplicacion1/templates/listadoempleado.html
{% extends 'base.html' %}

{% block contenido %}

<center><h2>Listado de empleados</h2>  </center> 
<br>
<table border="1" class="table table-striped">
	<tr>
		<td class="danger"><font size ="3", color="black"><strong>Codigo empleado</strong></td>
		<td class="danger"><font size ="3", color="black"> <strong>Nombre empleado</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>E-mail</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>Fecha de inicio</strong></td>
		<td class= "danger"><font size ="3", color="black"><strong>Acciones</strong></td>
		
	</tr>
	{% for  est in object_list %}
	<tr>
		<td > {{ est.codigo_empleado}}</td>
		<td > {{ est.nombre_empleado}}</td>
		<td > {{ est.email_empleado}}</td>
		<td > {{ est.fecha_empleado}}</td>
			<td>
			<a class="btn btn-primary" href="{% url 'app1:editar_empleado' est.codigo_empleado %}">Editar</a>
			<a class="btn btn-primary" href="{% url 'app1:eliminar_empleado' est.codigo_empleado %}">Eliminar</a>
			
		</td>


	</tr>
	
	
	{% endfor %}
	<br>
	<div>
		<div class="form-group">
			<center> 
			<a href="{% url 'app1:empleado' %}"><strong><u><font size ="5", color="#2271b3">Crear un nuevo empleado</font></u></strong></a>
			</center>
		</div>
			
	</div>
</table>


{% endblock %}

Apps/Aplicacion1/templates/listadoinventario.html
{% extends 'base.html' %}

{% block contenido %}

<center> 
<h2>Listado de productos</h2>
</center>
<br>
<table border="1" class="table table-striped">
	<tr>
		<td class="danger"><font size ="3", color="black"><strong>Codigo inventario</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>Nombre producto</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>Marca</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>Existencia</strong></td>
		<td class="danger"><font size ="3", color="black"><strong>Precio</strong></td>
		<td class= "danger"><font size ="3", color="black"><strong>Acciones</strong></td>
	</tr>
	{% for  inventario in object_list %}
	<tr>
		<td> {{ inventario.codigo_inventario}}</td>
		<td> {{ inventario.nombre_inventario}}</td>
		<td> {{ inventario.marca_invetario}}</td>
		<td> {{ inventario.existencia_inventario}}</td>
		<td> {{ inventario.precio_inventario }}</td>
		<td>
			<a class="btn btn-primary" href="{% url 'app1:editar_inventario' inventario.codigo_inventario %}">Editar</a>
			<a class="btn btn-primary" href="{% url 'app1:eliminar_inv' inventario.codigo_inventario %}">Eliminar</a>
		</td>

	</tr>
	{% endfor %}
	<div>
				<div class="form-group">
				
			<center>   	<a href="{% url 'app1:inventario' %}"><strong><u><font size ="5", color="#2271b3">Ingresar nuevo producto</font></u></strong></a>
			</center>	
			
				</div>
					
		</div>
</table>


{% endblock %}